# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0b88f78f406d2604ef6005e96c5fca4a15a218e946dc10261ac67f538f681d73a54d16502fb878f7cbac5116790a1f2fa535e6f5c201b06a1f503cb563fa14b

test:
  secret_key_base: 7185e205103ab496881052d75a932e27d190fc64ddd375e13cd9acd61948edc4208596edd28a89814d3ddd711fd0b219715d0d05ea5439fe42e78c88276afdb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
